name: aqar_map_task
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  #cupertino_icons: for ios icons
  cupertino_icons: ^1.0.8
  #flutter_screenutil: for responsive design
  flutter_screenutil: ^5.9.3
  #dio: for api calls
  dio: ^5.7.0
  #get_it: for dependency injection
  get_it: ^8.0.1
  #shared_preferences: for local storage
  shared_preferences: ^2.3.2
  #flutter_secure_storage: for secure local storage
  flutter_secure_storage: ^9.2.2
  #flutter_offline: for checking internet connection
  flutter_offline: ^4.0.0
  #flutterBloc: for state management
  flutter_bloc: ^8.1.6
  #freezed_annotation: for code generation
  freezed_annotation: ^2.4.4
  #pretty_dio_logger: for logging api calls
  pretty_dio_logger: ^1.4.0
  #go_router: for routing
  go_router: ^14.3.0
  #json_annotation: for json serialization
  json_annotation: ^4.9.0
  #flutter_svg: for svg images
  flutter_svg: ^2.0.10+1
  #cached_network_image: for caching network images
  cached_network_image: ^3.4.1
  #freezed: for code generation
  freezed: ^2.5.7
  #equatable: for value equality
  equatable: ^2.0.5
  #retrofit: for api calls
  retrofit: ^4.4.1
  #retrofit_generator: for code generation
  retrofit_generator: ^9.1.4
  #rxdart: for reactive programming
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  #build_runner: for code generation
  build_runner: ^2.4.13
  #json_serializable: for json serializations
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
